version: '3.8'

services:
  findMyBuilding_db:
    image: mysql:latest
    container_name: findMyBuilding_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: findMyBuilding
      MYSQL_USER: findMyBuilding
      MYSQL_PASSWORD: findMyBuilding
    ports:
      - "3306:3306"
    volumes:
      - findMyBuilding_data:/var/lib/mysql

volumes:
  findMyBuilding_data:
